# .github/workflows/ci.yml

name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print current directory
      run: pwd
    
    - name: List files in the directory
      run: ls -R
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-md
    
    - name: Verify file presence
      run: |
        if [ ! -f "test_calculator.py" ]; then
          echo "File test_calculator.py not found!"
          exit 1
        fi
    
    - name: Run tests and generate markdown report
      run: |
        pytest test_calculator.py --md=pytest_report.md
    
    - name: Display markdown report
      run: |
        echo "## Pytest Markdown Report"
        echo '```markdown'
        cat pytest_report.md
        echo '```'
