name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify file presence
        run: |
          echo "Checking for test file..."
          if [ ! -f ".github/workflows/test_calculator.py" ]; then
            echo "File .github/workflows/test_calculator.py not found!"
            exit 1
          else
            echo "File .github/workflows/test_calculator.py found."
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install pytest pytest-markdown-docs
          pip list

      - name: Run pytest with markdown-docs
        run: |
          echo "Running pytest with markdown-docs..."
          pytest --markdown-docs --maxfail=1 --disable-warnings > pytest_report.md || echo "Pytest failed"
          cat pytest_report.md

      - name: Display markdown report
        run: |
          echo "## Pytest Markdown Report"
          echo '```markdown'
          cat pytest_report.md
          echo '```'
